# Generated by Django 4.0.6 on 2022-07-12 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 2, 29, 13, 716183)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 2, 29, 13, 715336)),
        ),
        migrations.AddIndex(
            model_name='chatrecord',
            index=models.Index(fields=['user'], name='chat_chatre_user_id_b1af1e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecord',
            index=models.Index(fields=['chatroom'], name='chat_chatre_chatroo_6cdd09_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecord',
            index=models.Index(fields=['send_time'], name='chat_chatre_send_ti_1fc602_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['name'], name='chat_chatro_name_b0f383_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['creator'], name='chat_chatro_creator_b8c3eb_idx'),
        ),
    ]
